language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed 
  - docker tag udagram-api-feed 1386aje/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user 1386aje/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend 1386aje/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy 1386aje/udagram-reverseproxy:v1
  - echo "-------- All images succesfully built----------"


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 1386aje/udagram-api-feed:v1
  - docker push 1386aje/udagram-api-user:v1
  - docker push 1386aje/udagram-frontend:v1
  - docker push 1386aje/udagram-reverseproxy:v1

  - echo "-------------PUSHED TO DOCKER HUB WITHOUT NO ISSUES---------"


